package com.anafthdev.dujer.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006684)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFbae9ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f2a)
val md_theme_light_secondary = Color(0xFF4c616b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd0e6f2)
val md_theme_light_onSecondaryContainer = Color(0xFF081e27)
val md_theme_light_tertiary = Color(0xFF5d5b7d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFe3dfff)
val md_theme_light_onTertiaryContainer = Color(0xFF1a1836)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFf4f6f6)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFDFE6EE)
val md_theme_light_onSurfaceVariant = Color(0xFF40484c)
val md_theme_light_outline = Color(0xFF70787d)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1f3)
val md_theme_light_inverseSurface = Color(0xFF2e3133)
val md_theme_light_inversePrimary = Color(0xFF63d3ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF63d3ff)
val md_theme_dark_onPrimary = Color(0xFF003547)
val md_theme_dark_primaryContainer = Color(0xFF004d65)
val md_theme_dark_onPrimaryContainer = Color(0xFFbae9ff)
val md_theme_dark_secondary = Color(0xFFb4cad6)
val md_theme_dark_onSecondary = Color(0xFF1f333c)
val md_theme_dark_secondaryContainer = Color(0xFF354a54)
val md_theme_dark_onSecondaryContainer = Color(0xFFd0e6f2)
val md_theme_dark_tertiary = Color(0xFFc6c2ea)
val md_theme_dark_onTertiary = Color(0xFF2f2d4d)
val md_theme_dark_tertiaryContainer = Color(0xFF454365)
val md_theme_dark_onTertiaryContainer = Color(0xFFe3dfff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e4)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e4)
val md_theme_dark_surfaceVariant = Color(0xFF40484c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c8cd)
val md_theme_dark_outline = Color(0xFF8a9296)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e2e4)
val md_theme_dark_inversePrimary = Color(0xFF006684)
val md_theme_dark_shadow = Color(0xFF000000)

val black01 = Color(0xFF020202)
val black02 = Color(0xFF1C1C1C)
val black03 = Color(0xFF353535)
val black04 = Color(0xFF4F4F4F)
val black05 = Color(0xFF686868)
val black06 = Color(0xFF818181)
val black07 = Color(0xFF9A9A9A)
val black08 = Color(0xFFB3B3B3)
val black09 = Color(0xFFCDCDCD)
val black10 = Color(0xFFF0F0F0)

val seed = Color(0xFF37474f)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFFc1d34d)
val incomeColor = Color(0xFF6AC03F)
val expenseColor = Color(0xFFE23636)
val saveColor = Color(0xFF8AEC59)
val warningColor = Color(0xFFE7E552)
val dangerColor = Color(0xFFFD3939)
val swipe_dismiss_delete_background = Color(0xFFFFA1A1)
val swipe_dismiss_edit_background = Color(0xFFABFF9C)

val balance_card_background = Color(0xFF37474F)
val income_card_background = Color(0xFFD6EBE8)
val expense_card_background = Color(0xFFE6E2E6)
