package com.anafthdev.dujer.foundation.uicomponent.charting.tokens

enum class ChartingColorSchemeKeyTokens {
	Background,
	Error,
	ErrorContainer,
	InverseOnSurface,
	InversePrimary,
	InverseSurface,
	OnBackground,
	OnError,
	OnErrorContainer,
	OnPrimary,
	OnPrimaryContainer,
	OnSecondary,
	OnSecondaryContainer,
	OnSurface,
	OnSurfaceVariant,
	OnTertiary,
	OnTertiaryContainer,
	Outline,
	Primary,
	PrimaryContainer,
	Secondary,
	SecondaryContainer,
	Surface,
	SurfaceTint,
	SurfaceVariant,
	Tertiary,
	TertiaryContainer,
}